### ISSUE TITLE
提交一下在1.0.0版本测试的bug和建议

### ISSUE THREAD

**Issue by xyh2274** [leck995/Asmr-Player#1]
首先先向UP无偿开发音声播放器的付出和贡献表示感谢
接下来是个人在测试时的一些感受。

 一、bug
1. 刮削标签和封面等信息后不会识别本地信息文件内的lrc文件，不显示字幕标签

二使用体验建议
1. 建议在主界面除字幕和全年龄标签外，也可设置是否显示音声本身的全部标签信息。（初步猜测是不会在有多层文件夹时向下层文件夹检测是否存在lrc文件）
2. 刮削的标签和封面会存储在音声文件夹内，建议设置是否在客户端本身目录下生成对应资源库专门存储该资源，而非在音声文件夹内生成，以便于保证音声文件夹本身的整洁性。
3. 个人建议可以参考基于[kioeru](https://github.com/kikoeru-project/kikoeru-express)的音声[asmr.one](https://asmr.one/works)的部分功能实现

**Comment by leck995** [comment]
自动识别本地lrc来判断字幕是否存在的功能其实并没有做，最初的设计理念是约定大于配置，后面会进行添加该功能；
如果你查看音声目录，会细心的发现，同步时只会有两个封面文件，一个是cover-thumb,一个是cover-main,main存在的目的就是为了实现大图模式；
后续同样会在设置中添加选择封面数据保存位置的选项；
