### ISSUE TITLE
能否支持记录播放进度

### ISSUE THREAD

**Issue by ayanami-desu** [leck995/Asmr-Player#2]
重启软件后能恢复上一次的播放进度
或者记录所有文件的播放进度

**Comment by leck995** [comment]
后续会添加记忆播放功能；
现在可以在GalGame模式下使用保存与加载功能记录与恢复播放进度

**Comment by ayanami-desu** [comment]
进度保存好像只是保存了一张图片？要如何读取进度？
让人很迷糊

**Comment by ayanami-desu** [comment]
参考首页的图，似乎是出bug了，我这里无法正常保存。

**Comment by leck995** [comment]
操作逻辑和Galgame相似，如果无法保存建议重新尝试，或者重启后再试。
