### ISSUE TITLE
遇到的几个问题

### ISSUE THREAD

**Issue by smiledrunk** [leck995/Asmr-Player#3]
1.部分dl已经下架的作品在民间有留档，强迫症表示只有这些作品始终不能同步很难受。可能是分辨率的问题，即使手动设置非dl网站上下载下来的图片仍旧不能设置为封面。
2.目前试了一下，基本做不到除了dlsite以外的网站对音声进行同步（也有可能是我知道的网站太少），不知道后面的版本是否会追加。
3.在音声总览界面我看到目前只有4种排序方式，有没有办法对总览界面自定义，比如部分gal的游戏特典音声不在dl上贩卖，因此无法同步而且设置不了封面有点头疼。

**Comment by leck995** [comment]
对于无法同步到的音声。软件支持自定义封面，一共有两种方法：
1.在软件安装目录resource\cover，根据Rj号添加封面
2.在音声目录，将封面名称设置为cover-thumb和cover-main。
当然，如你所说分辨率的问题确实存在，我曾进行优化，但因为某些原因迫不得已舍弃该功能，目前最佳体验的封面比例在4:3,例如240*180，400*300的分辨率的封面，目前只能靠你通过其他软件修改

目前只支持D站同步，我之所以将同步放在插件一栏中，是因为在设计之初，将同步功能作为可扩展的插件，这样就可以灵活的实现适配多种同步源，但目前我在技术上遇到了一些难题迟迟无法解决。

关于第三条，排序后面也会进行优化，但我有点没有理解你的表达意思

**Comment by smiledrunk** [comment]
感谢答复，目前封面能改之后可以通过手动修改的方式达到效果了，祝往后越来越好。
